docs: ✏️ add mental-health-oss-zh
antfu/antfu.me pull request #74
Opened 2024-03-19 02:37 UTC by xxholly32

### Description

mental-health-oss 中文翻译

### Additional context

大部分用的是 ai + 个人校验，可能还有不通顺或者不足之处

有些句子加入了自己的思考，比如标题等可能需要关注下

里面有几个TODO，个人也想不好怎么翻译或者美观上会有一些影响的地方

2024-03-19 10:37 UTC, antfu commented
感谢翻译 - 但说实话这 AI 翻译的效果差强人意，要表达原意可能会需要大量的时间校验。也许我之后可以写篇中文，但也不确定，这篇文章的本意更像是篇日记，并没有”大肆推广“的意图，不太确定是否值得这么做

2024-03-19 11:01 UTC, xxholly32 commented
ok

2024-03-19 11:09 UTC, antfu commented
我已经开始 review 了，虽然要花点时间，这个 PR 就开着我慢慢改吧 🤣

2024-03-23 22:26 UTC, yyyanghj requested changes
前几天我也翻译了一些，人工翻译后用 GPT 进行了一些润色，主要还是意译，供参考。

2024-03-23 22:26 UTC, yyyanghj commented on pages/posts/mental-health-oss-zh.md
> +我可能不愿意承认我潜在的疲劳。不是因为我害怕，而是更像是，我不想放弃，被动地处理它。我知道需要休息时要休息，但称自己为“疲劳”并放弃是一种“逃避责任”的“捷径”。我想找出“根本原因”，并尝试改善情况，而不是只是“绕过”它。正如我们之前讨论的，对“期望”的转变，以及对我“准备不足”和“自我期望”的重新评估是我在不同原因下接近疲劳时的解决方案。通过调整自己和接纳现实，我通常能在大约一周的时间内从低谷
```suggestion
我可能不愿意承认我潜在的倦怠。这并不是因为我害怕，而是我不想轻言放弃，也不想被动地去应对。我知道需要休息时要休息，但称自己为“倦怠”并放弃对我来说像是一种“逃避责任”的“捷径”。我想找出“根本原因”，并尝试改善情况，而不仅仅是「临时应对」。正如我们之前讨论的，对“期望”的转变，重新审视自己的“措手不及”和“自我期望”，是我在因不同原因而面临倦怠时的解决方案。通过自我调整和适应，我通常能在大约一周的时间内走出低谷，并继续前进。
```

2024-03-23 22:26 UTC, yyyanghj commented on pages/posts/mental-health-oss-zh.md
> +这次的情况有点不同，不是因为我没有动力，而是因为我想做的事情太多了，但我已经没有了容量。我开始思考，也许是我期望自己保持以相同的<b important-text-hex-E3B65E>速度</b>交付一切，我对做得不够和做得不快感到焦虑。快速获得反馈是很棒的，也很高效，但我可能因为太习惯于快速而变得有些不耐烦。结合起来，当我在做一些需要中长期努力的事情时，我很容易感到沮丧。
```suggestion
这次的情况有点不同，并不是因为我缺乏动力，而是因为我想做的事情太多了，而是因为我想做的事情太多，超出了我的承受能力。我开始思考，或许问题在于我总是抱着保持<b important-text-hex-E3B65E>速度</b>并且不断交付成果这种期望，我对做得不够和做得不快感到焦虑。快速获得反馈是很棒的，也很高效，但我可能因为太习惯于快速而变得有些不耐烦。这些因素叠加在一起，当我在做一些需要中长期努力的事情时，我很容易感到沮丧。
```

2024-03-23 22:26 UTC, yyyanghj commented on pages/posts/mental-health-oss-zh.md
> +例如，_写作_。我不擅长写作，而且我并不真的喜欢它。文档、博客文章、教程和演讲 —— 都需要很多时间，也是我必须做的事情。当我在写作时，我很容易分心和失去专注，或者在中途放弃。所以我在 [Twitter 上询问了一下](https://twitter.com/antfu7/status/1764397930796953823)，得到了社区的很多很好的建议（看看评论，你可能也会找到对你有用的东西）
```suggestion
例如，_写作_。我不擅长写作，而且我也并不喜欢写作。文档、博客文章、教程和演讲 —— 都需要耗费大量时间，但我又不得不做。当我在写作时，我很容易失心和分身，或者中途放弃。所以我在 [Twitter 上询问了一下](https://twitter.com/antfu7/status/1764397930796953823)，得到了社区的很多很好的建议（看看评论，对你来说也许也有帮助）。我开始尝试放轻松，慢慢地做，试图转变我的思维，不急于求成，享受过程。你正在阅读的这篇博客大约花了我一周的时间来写（对我来说这是相当长的时间），分成了多个阶段来完成。这也帮助我重新审视和梳理我的思想和感受，实际上，把它们写下来也减轻了我的焦虑感。
```

2024-03-23 22:26 UTC, yyyanghj commented on pages/posts/mental-health-oss-zh.md
> +所以，我可能应该重新评估我的容量和期望。我必须理解并接受，我并不总是能保持相同的速度，也不必逼自己太紧。放慢一点，更多地关注细节，也许我会在过程中找到不同的快乐和满足感。
```suggestion
因此，我应该重新审视一下自己的承受力和期望值。我得明白并接受一个事实：我不可能始终以这样的速度前进，也没必要对自己过于严苛。放缓步伐，更细致地打磨每一个细节，也许我能在这个过程中找到别样的快乐和满足感。
```

2024-03-23 22:26 UTC, yyyanghj commented on pages/posts/mental-health-oss-zh.md
> +老实说，我甚至不确定我在这篇博客文章中想要表达什么 —— 也许只是简单地与你分享我的想法和感受。现在，我仍然感到相当大的压力。我仍在适应和努力寻找更好的处理方式。在这一周的写作和与朋友交谈中，我感觉好多了，我相信我会度过这个难关。这可能就像我们生活中的许多其他事情一样；我们并不总是有完美的解决方案，但我们必须继续前进，找到自己的出路。
```suggestion
老实说，我并不确定我在这篇博客文章中想要表达什么 —— 也许只是简单地与你分享我的想法和感受。现在，我仍然感到相当大的压力。我仍在适应和努力寻找更好的处理方式。通过这一周的写作和与朋友交谈中，我感觉好多了，我相信我会度过这个难关。这可能就像我们生活中的许多其他事情一样；我们并不总是有完美的解决方案，但我们必须得继续前进，找到出路。
```

2024-03-23 22:26 UTC, yyyanghj commented on pages/posts/mental-health-oss-zh.md
> +保持良好的心理健康是每个开源维护者保持可持续性的重要任务之一。我不认为在整个旅程中会有“一个答案”或“一个解决方案”。这更像是一个持续的学习和适应的过程，找到适合我们每个人的方法。
```suggestion
对于每个开源项目维护者来说，保持良好的心理健康是实现长期可持续发展的关键。在整个旅程中，我不认为会有一个统一的“答案”或“解决方案”。这更像是一个持续的学习和适应的过程，去寻找适合我们每个人的方法。
```

2024-03-23 22:26 UTC, yyyanghj commented on pages/posts/mental-health-oss-zh.md
> +**谢谢**你读完了我混乱而冗长的心情直到最后！
```suggestion
**感谢**你能耐心地把我这杂乱冗长的心情读到最后！
```

2024-03-23 22:26 UTC, yyyanghj commented on pages/posts/mental-health-oss-zh.md
> +我知道我的观点一定是非常偏见的。如果它曾经引发了你的一些想法或感受，我**很想听听你的想法或你的方法**。你可以在这个 [推文](https://twitter.com/antfu7/status/1768973757681438909) 或 [mastodon](https://elk.zone/m.webtoo.ls/@antfu/112105304547243075) 下留下一些评论，或者
```suggestion
我知道我的观点一定是非常偏见的。如果它曾经引发了你的一些想法或感受，我**很想听听你的想法或你的方法**。你可以在这个 [推文](https://twitter.com/antfu7/status/1768973757681438909) 或 [mastodon](https://elk.zone/m.webtoo.ls/@antfu/112105304547243075) 下评论，如果你更喜欢私下交流，也可以发邮件到 hi@antfu.me。
```

2024-03-23 22:26 UTC, yyyanghj commented on pages/posts/mental-health-oss-zh.md
> +与此同时，实际上关于开源还有很多其他事情我在这篇文章中没有谈到。[Artem Zakharchenko](https://twitter.com/kettanaito) 写了一篇很棒的文章 [开源的黑暗面](https://kettanaito.com/blog/the-dark-side-of-open-source)，从不同的角度和观点，我也非常认同。强烈推荐你也读一读。
```suggestion
另外，还有许多关于开源方面的话题，我在这篇文章里没有提及。[Artem Zakharchenko](https://twitter.com/kettanaito) 写了一篇相当精彩的文章 [开源的黑暗面](https://kettanaito.com/blog/the-dark-side-of-open-source)，他从不同的角度和观点出发，我也非常认同。强烈推荐你也读一读。
```

2024-03-23 22:26 UTC, yyyanghj commented on pages/posts/mental-health-oss-zh.md
> +### 感谢
```suggestion
### 致谢
```

2024-03-23 22:26 UTC, yyyanghj commented on pages/posts/mental-health-oss-zh.md
> +最后，我要非常感谢我的女朋友 [Inès](https://www.instagram.com/iiiiiiines__/)，她从一开始就一直支持我，帮助我度过了那些艰难的时刻。没有她的大力支持，我可能今天不会在开源中。
```suggestion
最后，我要非常感谢我的女朋友 [Inès](https://www.instagram.com/iiiiiiines__/)，她一直支持我，从始至终陪伴我度过每一个艰难的时刻。如果没有她的支持，我的开源之路也许不会走到今天。
```

2024-03-25 10:07 UTC, antfu commented
感谢翻译 @xxholly32 @yyyanghj！

2024-03-25 10:07 UTC, merged